version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    env_file: .env
    container_name: account-api
    network_mode: host
    depends_on:
      - mongodb

  mongodb:
      image: mongo:4.2.5
      container_name: account-mongodb
      restart: always
      volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      ports:
        - "${DB_PORT}:27017"
      environment: 
        - MONGO_INITDB_DATABASE=${DB_DATABASE}
      networks:
        - account-network
  
networks:
  account-network:
    driver: bridge
