version: '3.7'

services: 
  mongodb:
      image: mongo:4.2.5
      container_name: account-mongodb
      restart: always
      ports:
        - "${DB_PORT}:27017"
      networks:
        - account-network
  
networks:
  account-network:
    driver: bridge
