version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: dockerfile.dev
    restart: always
    env_file: .env
    ports: 
      - "${APP_PORT}:${APP_PORT}"
    container_name: account-api
    networks:
        - account-network
    depends_on:
      - mongodb

  mongodb:
      image: mongo:4.2.5
      container_name: account-mongodb
      restart: always
      ports:
        - "${DB_PORT}:27017"
      environment: 
        - MONGO_INITDB_DATABASE=${DB_DATABASE}
      networks:
        - account-network
  
networks:
  account-network:
    driver: bridge
